networks:
  backend: null
  frontend: null
services:
  db:
    deploy:
      placement:
        constraints:
        - node.role == manager
        preferences:
        - spread: node.labels.ip == 83.212.98.176
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:9.4
    networks:
    - backend
    volumes:
    - db-data:/var/lib/postgresql/data
  redis:
    deploy:
      placement:
        preferences:
        - spread: node.labels.ip == 83.212.98.176
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        parallelism: 2
    image: redis:alpine
    networks:
    - frontend
  result:
    depends_on:
    - db
    deploy:
      placement:
        preferences:
        - spread: node.labels.ip == 83.212.102.89
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        parallelism: 2
    image: dockersamples/examplevotingapp_result:before
    networks:
    - backend
    ports:
    - 5001:80
  visualizer:
    deploy:
      placement:
        constraints:
        - node.role == manager
    image: dockersamples/visualizer:stable
    ports:
    - 8080:8080
    stop_grace_period: 1m30s
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  vote:
    depends_on:
    - redis
    deploy:
      placement:
        preferences:
        - spread: node.labels.ip == 83.212.102.89
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
    image: dockersamples/examplevotingapp_vote:before
    networks:
    - frontend
    ports:
    - 5002:80
  worker:
    depends_on:
    - db
    - redis
    deploy:
      labels:
      - APP=VOTING
      mode: replicated
      placement:
        constraints:
        - node.role == manager
        preferences:
        - spread: node.labels.ip == 83.212.102.89
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    image: dockersamples/examplevotingapp_worker
    networks:
    - frontend
    - backend
version: '3.3'
volumes:
  db-data: null
